import { FontConfig } from "~/context/app/interfaces";

/** Shape of the message content sent to the iframe in preview */
export interface Message {
  // The code of the stylesheet generated by the Tipography state
  stylesheetTypographyCode: string;
  // The code of the stylesheet generated by MediaQueries state
  stylesheetMediaQueriesCode: string;
  // The font family of the heading
  fontHeading: FontConfig;
  // The font family of the body
  fontBody: FontConfig;
}

/** Information used by the "contentWindow.postMessage()" function */
export interface PostMessage {
  /** The ref of iframe window required for the "contentWindow.postMessage()" function */
  iframeRef: React.RefObject<HTMLIFrameElement>;
  // The shape of the message sent to the iframe
  message: Message;
}
