import { FontConfig } from "~/context/app/interfaces";

/** Shape of the message content sent to the iframe in preview */
export interface MediaQueriesMessage {
  // The code of the stylesheet generated by MediaQueries state
  stylesheetMediaQueriesCode?: string;
}

/** Shape of the message content sent to the iframe in preview */
export interface TypographyMessage {
  // The code of the stylesheet generated by the Tipography state
  stylesheetTypographyCode?: string;
  // The font family of the heading
  fontHeading?: FontConfig | undefined;
  // The font family of the body required to create the Google Fonts <link> tag on the iframe preview
  fontBody?: FontConfig | undefined;
}

export type Message = MediaQueriesMessage & TypographyMessage;

/** Information used by the "contentWindow.postMessage()" function */
export interface PostMessage {
  /** The ref of iframe window required for the "contentWindow.postMessage()" function */
  iframeRef: React.RefObject<HTMLIFrameElement>;
  // The shape of the message sent to the iframe
  message: Message;
}
