export default function useBreakpointsRoutes() {
  const ROUTE_BREAKPOINTS_BASE_ROUTE = "/breakpoints";
  const ROUTE_BREAKPOINTS_LIST = `${ROUTE_BREAKPOINTS_BASE_ROUTE}/list`;
  const ROUTE_BREAKPOINTS_ERROR_MISSING_BREAKPOINTS = `${ROUTE_BREAKPOINTS_BASE_ROUTE}/missing-breakpoints`;
  const ROUTE_BREAKPOINTS_NEW = `${ROUTE_BREAKPOINTS_BASE_ROUTE}/edit/new`;
  const ROUTE_BREAKPOINTS_UPDATE = `${ROUTE_BREAKPOINTS_BASE_ROUTE}/edit`;

  return {
    ROUTE_BREAKPOINTS_BASE_ROUTE,
    ROUTE_BREAKPOINTS_LIST,
    ROUTE_BREAKPOINTS_ERROR_MISSING_BREAKPOINTS,
    ROUTE_BREAKPOINTS_NEW,
    ROUTE_BREAKPOINTS_UPDATE,
  };
}
