export const FS_CONTEXT_BREAKPOINTS = "FS_CONTEXT_BREAKPOINTS";
export const FS_CONTEXT_MEDIA_QUERIES = "FS_CONTEXT_MEDIA_QUERIES";
export const FS_CONTEXT_SELECTORS = "FS_CONTEXT_SELECTORS";
export const FS_CONTEXT_STEPS = "FS_CONTEXT_STEPS";
export const FS_CONTEXT_TYPESCALE = "FS_CONTEXT_TYPESCALE";
