export const FS_CONTEXT_BREAKPOINTS = "FS_CONTEXT_BREAKPOINTS";
export const FS_CONTEXT_MEDIA_QUERIES = "FS_CONTEXT_MEDIA_QUERIES";
export const FS_CONTEXT_TYPESCALE_STEPS = "FS_CONTEXT_TYPESCALE_STEPS";
export const FS_CONTEXT_TYPESCALE_CONFIG = "FS_CONTEXT_TYPESCALE_CONFIG";
export const FS_CONTEXT_TYPOGRAPHY = "FS_CONTEXT_TYPOGRAPHY";
